### ISSUE TITLE
Upload downloaded konfliktinteresa.me website

### ISSUE THREAD

**Issue by KrzysztofMadejski** [cdtcrnagora/konfliktiinteresa#1]

**Comment by KrzysztofMadejski** [comment]
Damir:  "it's 1gb something"

Wow, why it's 1GB? It's just HTML tables and few logos. Maybe there is some external resources that should be stripped?

**Comment by Ksktozt** [comment]
Hi there :)

http://cdtmn.org/assets/konfliktiinteresa%20offline.zip

Here is what i've downloaded using HTTrack Website Copier, since i couldn't make it completely offline by just saving site as... asset cards are an iframe.
